druid.server.http.numThreads=6
druid.query.scheduler.numThreads=2
druid.broker.http.numConnections=2
druid.broker.http.numMaxThreads=2
druid.broker.http.maxQueuedBytes=1MiB
druid.processing.buffer.sizeBytes=8MiB
druid.processing.numMergeBuffers=2
druid.processing.numThreads=1
druid.processing.merge.useParallelMergePool=false