druid.extensions.loadList=["druid-kafka-indexing-service","druid-protobuf-extensions"]
druid.host=localhost
druid.bindOnHost=true
druid.startup.logging.logProperties=false
druid.cache.sizeInBytes=0
druid.manager.segments.killUnused.enabled=false
druid.coordinator.kill.on=false
druid.indexer.logs.kill.enabled=false