druid.indexer.runner.type=local
druid.indexer.runner.javaOptsArray=["-server","-Xms256m","-Xmx256m","-XX:MaxDirectMemorySize=300m","-Duser.timezone=UTC","-Dfile.encoding=UTF-8","-XX:+ExitOnOutOfMemoryError","-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager"]
druid.indexer.fork.property.druid.processing.numMergeBuffers=2
druid.indexer.fork.property.druid.processing.buffer.sizeBytes=25MiB
druid.indexer.fork.property.druid.processing.numThreads=1
druid.indexer.queue.startDelay=PT2S
druid.coordinator.startDelay=PT5S
druid.coordinator.period=PT5S
druid.manager.segments.pollDuration=PT5S