druid.server.http.numThreads=6
druid.processing.buffer.sizeBytes=8MiB
druid.processing.numMergeBuffers=2
druid.processing.numThreads=1
druid.segmentCache.locations=[{"path":"var/druid/segment-cache","maxSize":"5GiB"}]
druid.historical.cache.useCache=false
druid.historical.cache.populateCache=false