services:
  kafka-exporter:
    image: danielqsj/kafka-exporter:v1.8.0
    command:
      - --kafka.server=kafka:9092
      - --web.listen-address=:9308
      - --topic.filter=^(LiveMeasurement|Event|Alarm|Export|Masterdata|Schema|Blobmeta)$
      - --group.filter=.*
    depends_on:
      kafka:
        condition: service_healthy
    restart: unless-stopped