name: ${WAMA_PROCESSORS_COMPOSE_PROJECT_NAME:-wama-processors}

include:
  # provisioned-processor-includes:start
  - ./processors/processor-apparent-power/compose.yaml
  - ./processors/processor-frequency-scale/compose.yaml
# provisioned-processor-includes:end

services: {}

networks:
  wama-infra:
    external: true
    name: ${WAMA_INFRA_NETWORK:-wama-infra}