name: ${WAMA_PROCESSOR_COMPOSE_PROJECT_NAME:-wama-processor-frequency-scale}

services:
  processor-frequency-scale:
    image: "${WAMA_PROCESSOR_IMAGE:-wama.local/processor-frequency-scale:main}"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - wama-infra
    restart: unless-stopped

networks:
  wama-infra:
    external: true
    name: ${WAMA_INFRA_NETWORK:-wama-infra}
