syntax = "proto3";

package rtd_schema.v1;

import "google/protobuf/timestamp.proto";

// Measurement Values are intended to be primitives.
// Primitives are the only way to achieve high flexibility in the
// usage of the measurement value. The schema is designed to
// reflect this accordingly.
message MCCSMeasurementValue {
    // The mrid of the associated Measurement.
    string mrid = 1;

    // The timestamp of the value, reflecting the time when the value was generated in the field.
    // Optional, since not all MCCSMeasurementValues are originating from the field (e.g. internally
    // generated MeasurementValues) or field-generated data might not have a timestamp (e.g. caused by
    // the raw value being produced due to a general interrogation).
    optional google.protobuf.Timestamp timestamp_field = 2;

    // A timestamp reflecting the time when the value was transmitted by the gateway.
    // Optional, since not all MCCSMeasurementValues are originating from the field
    // and hence might not go through a gateway.
    optional google.protobuf.Timestamp timestamp_gateway = 3;

    // A timestamp reflecting the initial generation time of the value
    // inside of MCCS. (same as kafka message timestamp)
    // Non-optional since it always must be set by the producing service.
    // In general there hold the inequality timestamp_field <= timestamp_gateway <= timestamp_mccs
    google.protobuf.Timestamp timestamp_mccs = 4;

    // Fields 5-9 are reserved for future timestamp extensions.

    // The actual value of the measurement.
    // The value is one of the primitives defined in the oneof.
    // Any interpretation of these values is in the context of Master Data via a configuration
    // effort in the consuming module/service.
    oneof value {
        // double_value: Used for floating point measurements, e.g. active power, reactive power, voltage, temperature, wind speed, etc.
        double double_value = 10;

        // int_value: Used for integer measurements, e.g. tap position for transformers and shunts, or in general an ordered discrete state space. (not used for enumerated values, which are represented as uint_value).
        int64 int_value = 11;

        // uint_value: Runtime configurable enumerated values.
        // The interpretation of the uint_value is defined at engineering runtime
        // and can be used to represent enumerated state spaces, e.g. for switch or breaker status, but also
        // energized state or general multi way switch positions.
        // The interpretation of the value is handled via a ValueToAlias mapping at engineering time.
        // In general this value should be used for discrete state spaces,
        // which are not ordered and do not have a numerical meaning,
        // but rather represent different states of a measurement, e.g. switch status (open, closed),
        // or energized state (energized, de-energized, grounded, etc.).
        uint32 uint_value = 12;

        // bool_value: Used for boolean measurements, which represent binary states.
        bool bool_value = 13;

        // string_value: Used for string measurements, e.g. for status messages,
        // or e.g. interlocking texts.
        string string_value = 14;

        // timestamp_value: Used for timestamp measurements, e.g. for a timestamp in specific process pictures,
        // or just a timestamp value as a measurement in general.
        google.protobuf.Timestamp timestamp_value = 15;
    }

    // An incomplete list of quality indicators for the measurement value, which can be extended in the future as needed.
    message Quality {
        optional bool valid = 1;
        optional bool substituted = 2;
        optional bool operator_blocked = 3;
        optional bool overflow = 4;
        optional bool old_data = 5;
        // extend accordingly
    }

    Quality quality = 20;
}