apiVersion: 1

datasources:
  - name: Druid
    uid: druid
    type: grafadruid-druid-datasource
    access: proxy
    isDefault: false
    editable: false
    version: 1
    jsonData:
      connection.url: http://druid:8888