FROM data.forgejo.org/forgejo/runner:13

USER root

RUN apk add --no-cache \
    bash \
    ca-certificates \
    curl \
    docker-cli \
    docker-cli-compose \
    git \
    nodejs \
    npm \
    protobuf \
    py3-pip \
    py3-yaml \
    python3 \
    rsync